# Default values for androiddm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: androiddm
label: novnc

replicaCount: 1

image:
  repository: harbor.arfa.wise-paas.com/androiddm/novnc-ensaas
  tag: 1.0.0
  pullPolicy: IfNotPresent

imagePullSecrets: 
  name: regcred
service:
  name: novnc
  label: novnc
  type: ClusterIP
novncservice:
  name: novncsocket
  port: 9191
  targetPort: 9191
repeaterviewerservice:
  name: repviewersocket
  port: 5901
  targetPort: 5901
repeaterserverservice:
  name: repserversocket
  port: 5500
  targetPort: 5500

ingress:
  name: novnc
novncingress:
  host: novnc.androiddm.eks001.en.internal
repeatervieweringress:
  host: repeaterviewer.androiddm.eks001.en.internal
repeaterserveringress:
  host: repeaterserver.androiddm.eks001.en.internal

