# Default values for androiddm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: androiddm
label: androiddm

replicaCount: 1

image:
  repository: harbor.arfa.wise-paas.com/androiddm/m2mserver-ensaas
  tag: 1.0.0
  pullPolicy: Always

imagePullSecrets: 
  name: regcred

service:
  name: androiddm
  label: androiddm
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  name: androiddm
  host: androiddm.androiddm.eks001.en.internal

