apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.label}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.label}}
  template:
    metadata:
      labels:
        app: {{ .Values.label}}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name}}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.global.novnc.repository }}:{{ .Values.global.novnc.tag }}
        imagePullPolicy: {{ .Values.global.novnc.pullPolicy }}
        ports:
        - name: {{ .Values.novncservice.name }}
          containerPort: 9191
          protocol: TCP
        - name: {{ .Values.repeaterserverservice.name }}
          containerPort: 5500
          protocol: TCP
        - name: {{ .Values.repeaterviewerservice.name }}
          containerPort: 5901
          protocol: TCP
        resources:
          limits:
            cpu: 0.01    　　
            memory: 64M
            ephemeral-storage: 64M
          requests:
            cpu: 0.01
            memory: 64M
            ephemeral-storage: 64M
      
