apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels: 
    app: {{ .Values.service.label }}
spec:
  ports:
    - port: {{ .Values.repeaterserverservice.port }}
      targetPort: {{ .Values.repeaterserverservice.targetPort }}
      protocol: TCP
      name: {{ .Values.repeaterserverservice.name }}
    - port: {{ .Values.repeaterviewerservice.port }}
      targetPort: {{ .Values.repeaterviewerservice.targetPort }}
      protocol: TCP
      name: {{ .Values.repeaterviewerservice.name }}
    - port: {{ .Values.novncservice.port }}
      targetPort: {{ .Values.novncservice.targetPort }}
      protocol: TCP
      name: {{ .Values.novncservice.name }}
  selector:
    app: {{ .Values.label }}

  
