
{{- $ingressApiIsStable := eq (include "apphub.ingress.isStable" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "apphub.ingress.supportsPathType" .) "true" -}}
apiVersion: {{ include "apphub.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ .Values.novncIngress.name}}
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  rules:
  - host: {{ .Values.novncIngress.host }}{{.Values.global.url.host}}
    http:
      paths:
      - path: /
        {{- if $ingressSupportsPathType }}
        pathType: {{ .Values.global.ingress.pathType }}
        {{- end }}
        backend:
          {{- if $ingressApiIsStable }}
          service:
             name: {{ .Values.novncService.name }}
             port: 
               number: {{ .Values.novncService.port }}
          {{- else }}
          serviceName: {{ .Values.novncService.name }}
          servicePort: {{ .Values.novncService.port }}
          {{- end }}
