apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: androiddm
  name: androiddm
  namespace: gangqiang-test
spec:
  selector:
    matchLabels:
      app: androiddm
  template:
    metadata:
      labels:
        app: androiddm
    spec:
      containers:
      - name:  gq-androiddm
        image:  hub.docker.com/gangqiang01/m2mserver-ensaas:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          hostPort: 8080
        env:
        - name: appName
          value: androiddm
        - name: serviceName
          value: androiddm
        - name: ENSAAS_SERVICES
          valueFrom:
            secretKeyRef:
              name: androiddm
              key: ENSAAS_SERVICES
        resources:
          limits:
            cpu: 0.5     　　
            memory: 1G
            ephemeral-storage: 2G
          requests:
            cpu: 0.5
            memory: 1G
            ephemeral-storage: 2G
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
