apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}
  labels:
    app: {{ .Values.label}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.label}}
  template:
    metadata:
      labels:
        app: {{ .Values.label}}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name}}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.global.astore.repository }}:{{ .Values.global.astore.tag }}
        imagePullPolicy: {{ .Values.global.astore.pullPolicy }}
        ports:
        - name: http
          containerPort: 30001
          protocol: TCP
        env:
        - name: appName
          value: apphub
        - name: urlprefix
          value: {{ .Values.ingress.host }}
        - name: ssoUrl
          value: {{ .Values.global.ensaasApps.apiSso.internalUrl }}
        - name: serviceName
          value: apphub
        - name: pn
          value: {{ .Values.global.ensaasApps.licenseParam.pn }}
        - name: ENSAAS_SERVICES
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.database.secretName }}
              key: ENSAAS_SERVICES
        resources:
          limits:
            cpu: 0.1     　　
            memory: 512M
            ephemeral-storage: 1024M
          requests:
            cpu: 0.1
            memory: 512M
            ephemeral-storage: 1024M
      initContainers:
      - env:
        - name: NAMESPACE_NAME
          value: {{.Release.Namespace}}
        - name: POD_LABELS
          value: app=apphub-manager
        - name: MAX_RETRY
          value: "120"
        image: {{ .Values.global.podinit.repository }}:{{ .Values.global.podinit.tag }}
        imagePullPolicy: IfNotPresent
        name: pod-dependency
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      
