# Default values for androiddm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: androiddm
label: solutionapo

replicaCount: 1

image:
  repository: harbor.arfa.wise-paas.com/androiddm/solutionapp-ensaas
  tag: 1.0.0
  pullPolicy: IfNotPresent

imagePullSecrets: 
  name: regcred
service:
  name: solutionapp
  label: solutionapp
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  name: solutionapp
  host: portal-solutionapp

